language: node_js

node_js: 
  - "stable"
  
    
deploy:
  provider: pages
  skip_cleanup: true
  github_token: d4c8803da17c38535c62ff9aeed8b8f806d865f4 #$GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
    
    
